[package]
name = "ctap-hid-fido2"
version = "1.0.4"
authors = ["gebo <35388172+gebogebogebo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license="MIT"
description="Rust FIDO2 CTAP library"
repository="https://github.com/gebogebogebo/ctap-hid-fido2"
keywords=["FIDO2","CTAP"]
readme="README.md"

[dependencies]
serde_cbor = "0.11.1"
serde_derive = "1.0.116"
num = "0.3.0"
hex = "0.4.2"
byteorder = "1.3.4"
sha2 = "0.9.1"
ring = "0.13"
untrusted = "0.6"
rust-crypto = "0.2"
x509-parser = "0.8.0"
base64 = "0.13.0"


